json.id bookshelf.id
json.status bookshelf.status
json.rating bookshelf.rating
json.book_location bookshelf.book_location
json.format_type bookshelf.format_type
json.book bookshelf.book
json.book_id bookshelf.book_id
json.user_id bookshelf.id
json.user bookshelf.user